apiVersion: v1
kind: Service
metadata:
  name: deeptech-api
  namespace: deeptech-staging
  labels:
    app: deeptech-api
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: deeptech-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
